#!/usr/bin/env python3
"""Create a private two-NVIDIA-GPU config from a prepared Strata installation."""
from __future__ import annotations

import argparse
import copy
import json
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_PROFILE = ROOT / 'configs' / 'dual-nvidia-5070ti-128k.json'


def set_option(args: list[str], name: str, value: str | None) -> list[str]:
    result = []
    i = 0
    while i < len(args):
        if args[i] == name:
            if value is not None:
                if i + 1 >= len(args) or args[i + 1].startswith('--'):
                    raise ValueError(f'Missing value for {name}')
                i += 1
        else:
            result.append(args[i])
        i += 1
    return result + [name] + ([] if value is None else [value])


def apply_profile(config: dict, profile: dict, gpus: list[int], benchmark: bool = False,
                  draft_vocab: str | None = None, layer_split: str | None = None) -> dict:
    if len(gpus) != 2 or len(set(gpus)) != 2 or any(type(x) is not int or x < 0 for x in gpus):
        raise ValueError('Choose exactly two distinct NVIDIA GPU indices.')
    if not isinstance(profile, dict) or profile.get('schema_version') != 1 or profile.get('gpu_count') != 2:
        raise ValueError('Unsupported profile schema.')
    split = profile.get('layer_split', 'auto') if layer_split is None else layer_split
    if split != 'auto':
        if (type(split) not in (str, int) or not str(split).isascii() or not str(split).isdigit()
                or not 2 <= int(split) < 48):
            raise ValueError('Choose auto or a layer boundary from 2 to 47 for the 48-layer reference model.')
        split = str(int(split))
    options = profile.get('engine_options')
    if (not isinstance(options, dict) or not options
            or any(not isinstance(k, str) or not k.startswith('--')
                   or (v is not None and (not isinstance(v, str) or v.startswith('--')))
                   for k, v in options.items())
            or type(profile.get('conversation_checkpoints')) is not int
            or profile['conversation_checkpoints'] < 0):
        raise ValueError('Invalid profile options.')
    if not isinstance(config, dict) or not config.get('exe') or not config.get('tokenizer'):
        raise ValueError('Use a run config already generated by Strata setup.')
    args = config.get('args')
    if not isinstance(args, list) or not all(isinstance(x, str) for x in args):
        raise ValueError('The source config must contain a string argument list.')
    if any(x.split('=', 1)[0] in ['--batch', '--batch-mtp', '--slots', '--pipeline-windows',
                                 '--layer-split', '--split-device', '--split-skip-if-fits',
                                 '--trim-stage-weights'] for x in args):
        raise ValueError('Remove explicit batch/pipeline/split engine overrides before using this single-client profile.')
    if ('--mtp' not in args or args.index('--mtp') + 1 == len(args)
            or args[args.index('--mtp') + 1].startswith('--')):
        raise ValueError('Prepare the MTP draft with upstream setup before applying this profile.')
    if config.get('backend', 'cuda') not in ('cuda', None):
        raise ValueError('This profile is for NVIDIA CUDA installations.')
    result = copy.deepcopy(config)
    for name, value in options.items():
        if any(x.startswith(name + '=') for x in args):
            raise ValueError('Use separate flag and value arguments in the source config.')
        args = set_option(args, name, value)
    args = set_option(args, '--prompt-cache', '0' if benchmark else str(profile['conversation_checkpoints']))
    result.update(args=args, gpu=gpus, gpus_asked=True, layer_split=split, parallel=1,
                  open_browser=False, model_name='kervia-strata')
    result.pop('split_skip_if_fits', None)
    # Do not silently enable a model-changing control vector inherited from a local config.
    if any(x.startswith('--control-vector') for x in args):
        raise ValueError('Remove control vectors before applying the reference profile.')
    if draft_vocab is not None:
        result['draft_vocab'] = draft_vocab
    return result


def write_config(path: Path, config: dict) -> None:
    # Exclusive creation prevents accidental replacement; generated configs may contain local secrets.
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    with os.fdopen(fd, 'w', encoding='utf-8') as out:
        json.dump(config, out, indent=2)
        out.write('\n')


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--config', type=Path, required=True, help='Existing, prepared Strata run config')
    parser.add_argument('--profile', type=Path, default=DEFAULT_PROFILE)
    parser.add_argument('--gpus', default='0,1', help='Two nvidia-smi indices in stage order')
    parser.add_argument('--layer-split', help='Override profile placement: auto or a boundary from 2 to 47')
    parser.add_argument('--draft-vocab', choices=['cjk', 'en', 'fr', 'cyrillic'],
                        help='Optional prepared draft vocabulary; otherwise preserve the existing choice')
    parser.add_argument('--benchmark', action='store_true', help='Disable prefix checkpoints for uncached measurements')
    parser.add_argument('--output', type=Path, help='New local file, written with mode 0600; omission is a dry run')
    opts = parser.parse_args()
    try:
        gpus = [int(x) for x in opts.gpus.split(',')]
        config = json.loads(opts.config.read_text(encoding='utf-8'))
        profile = json.loads(opts.profile.read_text(encoding='utf-8'))
        updated = apply_profile(config, profile, gpus, opts.benchmark, opts.draft_vocab, opts.layer_split)
        if opts.output:
            write_config(opts.output, updated)
        print(f"{'Written' if opts.output else 'Dry run'}: two GPU stages {gpus}, "
              f"{'disabled' if opts.benchmark else 'enabled'} prefix cache.")
        print('Model paths, vision settings and credentials remain local. No service was started or changed.')
    except (ValueError, OSError, KeyError, TypeError) as error:
        # Never echo a config value, which could contain a credential.
        if isinstance(error, FileExistsError):
            parser.exit(2, 'Output already exists; choose a new filename.\n')
        parser.exit(2, f'Profile could not be applied ({type(error).__name__}). Check the source config and profile.\n')


if __name__ == '__main__':
    main()
